version: '3'

services:
  db:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '127.0.0.1:5432:5432'

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '127.0.0.1:6379:6379'

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    restart: unless-stopped
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      cluster.name: es-mastodon
      discovery.type: single-node
      bootstrap.memory_lock: 'true'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '127.0.0.1:9200:9200'
