name: Build container release customized images
on:
  push:
    tags:
      - '*genya0407*'
  workflow_dispatch:
    inputs:
      tags:
        type: string
        required: true

jobs:
  build-image:
    runs-on: codebuild-social-genya0407-link-${{ github.run_id }}-${{ github.run_attempt }}
    strategy:
      matrix:
        image:
          - { 'file': 'Dockerfile', name: 'mastodon' }
          - { 'file': 'streaming/Dockerfile', name: 'mastodon-streaming' }
    steps:
      - uses: actions/checkout@v4
      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/genya0407/mastodon/${{ matrix.image.name }}
          tags: ${{ inputs.tags }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.image.file }}
          platforms: linux/arm64
          provenance: false
          push: true
          tags: ${{ steps.meta.outputs.tags }}
